site_name: Seminar "Understanding Deep Learning" WS25/26
site_url: https://link-er.github.io/seminar_UDL_wise2526/   
repo_url: https://github.com/link-er/seminar_UDL_wise2526
docs_dir: docs
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.instant

nav:
  - Home: index.md
  - Schedule: schedule.md
  - Reports:
      - Week 01: reports/week02_ch3_4.md
      - Week 02: reports/week03.md
